spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        profile-name: default
      stack:
        auto: false

app:
  sqs:
    employee-queue: https://sqs.us-east-1.amazonaws.com/775727899903/MyFIFOQueue.fifo
