spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        profile-name: default
      stack:
        auto: false
      sqs:
        listener:
          task-executor-bean-name: sqsListenerTaskExecutor
          # max-concurrency: 5
          # min-concurrency: 2
          # max-messages-per-poll: 10
          # wait-time: 20

app:
  sqs:
    employee-queue: https://sqs.us-east-1.amazonaws.com/775727899903/MyFIFOQueue.fifo
